apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/rollout.yaml
- manifests/service.yaml
images:
- name: PROJECT/IMAGE
  newName: ollikarppinen/todo-frontend
  newTag: 834a972
