apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output-reader
          image: ollikarppinen/log-output
          imagePullPolicy: Always
          env:
            - name: LOG_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-config
                  key: log_message
        - name: log-output-writer
          image: ollikarppinen/log-output
          imagePullPolicy: Always
          command: ["npm"]
          args: ["run", "writer"]
