apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output-reader
          image: ollikarppinen/log-output
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-uuid
              mountPath: /app/shared
            - name: shared-ping-pong
              mountPath: /app/shared-ping-pong
        - name: log-output-writer
          image: ollikarppinen/log-output
          imagePullPolicy: Always
          command: ["npm"]
          args: ["run", "writer"]
          volumeMounts:
            - name: shared-uuid
              mountPath: /app/shared
      volumes:
        - name: shared-uuid
          emptyDir: {}
        - name: shared-ping-pong
          persistentVolumeClaim:
            claimName: shared-pv-claim
