apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/ollikarppinen/dev_ops_with_kubernetes
  ref:
    branch: main
