apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: ollikarppinen/ping-pong
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-ping-pong
              mountPath: /app/shared-ping-pong
      volumes:
        - name: shared-ping-pong
          persistentVolumeClaim:
            claimName: log-pv-claim
