apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
  namespace: log
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.3
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
                  optional: false
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              # subPath: postgres
      #       - name: postgres-script
      #         mountPath: /docker-entrypoint-initdb.d/init-db.sh
      #         subPath: init-db.sh
      # volumes:
      #   - name: postgres-script
      #     configMap:
      #       name: postgres-script
      #       defaultMode: 0777
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
