apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: log
data:
  init-db.sh: |
    #!/bin/sh

    set -e

    psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
      CREATE TABLE pingpongs (
        created_at TIMESTAMP NOT NULL
      );
    EOSQL
