apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: log
data:
  password: ENC[AES256_GCM,data:6F+VRhcIFIlX6mEn,iv:ckPlEkJ0Yys/66cA691Mx1ALcfeQCn58wOeGj7xZXq0=,tag:Xt8AXKWtvtI2yLVxZzfu4A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1k6608d8pzlhz0ffh8tlnax4mj0g7q4f3wggd68el69ruyhaegv0s9f5e9n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCa0hoUitlUm5qRGQvSklk
        NEJEc0ZlWnFpSlpGRXlpdDMwdUN2WkVQaTM4CnN2dXRXQUtva25Sa2owUXZwV3FK
        RStBUE1SOFUzMFVHejNSWHZsSk5wMEEKLS0tIHcxWHovcVhyL01FaVJlOVdSVHZL
        N2J0bTJ4VjlOTVFjZm55V1ZIL3lGK2MKRKU+Z8Zx1Gg7tIr9ad4MVab17rF9Ah/n
        4zAOGVZg+LQXpubLc+7J7ba3Hj8+UIxiHo11U/FX1IFxNVY6jmIF3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-06-18T20:49:26Z"
  mac: ENC[AES256_GCM,data:IBSSpzH1A8r9zZp+QDiNm0MqUMJgWFyZkU/Lmts+uffPwBiXY9ccQsvZI4rd2yCWLRkiD945VgTBs5mZb1T4ruYLR0bQ45mGXvalnezKIOd1vhdnfgZr2yN59jFI7QtI+6GVoB1iLnqbi7/Wu3rr1+q/N4sJZfm+bRvrpQmTJdU=,iv:Nh0HsRsPrnUwBZiY5XLu5NGzB9VEAKXvB8IH7MYtKCc=,tag:L+mP2kBjJ6gDjP+74a7UYA==,type:str]
  pgp: []
  encrypted_regex: ^(data)$
  version: 3.7.3
