apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: log
spec:
  type: NodePort
  selector:
    app: ping-pong
  ports:
    - name: public
      port: 2345
      protocol: TCP
      targetPort: 3000
    - name: internal
      protocol: TCP
      port: 80
      targetPort: 3000
