apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-image-cronjob
spec:
  schedule: "* 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: delete-image
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: shared-image
                  mountPath: /app/shared-image
              command:
                - /bin/sh
                - -c
                - rm /app/shared-image/image.jpg
          restartPolicy: OnFailure
          volumes:
            - name: shared-image
              persistentVolumeClaim:
                claimName: shared-pv-claim
