apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pv-claim
  namespace: log
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
