kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: todo-pv
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
  replication-type: regional-pd
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.gke.io/zone
        values:
          - eu-west-2b
