apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-rate
  namespace: todo
spec:
  metrics:
    - name: cpu-rate
      initialDelay: 2m
      interval: 1m
      count: 7
      successCondition: result < 0.1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1658-prometheus.prometheus.svc.cluster.local:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
          query: |
            scalar(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="todo"}))
