apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pv-claim
  namespace: todo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
