apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-frontend-dep
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: cpu-rate
        - pause:
            duration: 30s
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: PROJECT/IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "150m"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          env:
            - name: PERSISTED_IMAGE_PATH
              value: /app/shared-image/image.jpg
          volumeMounts:
            - name: shared-image
              mountPath: /app/shared-image
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: todo-pv-claim
