apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: todo
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: web
  clusterIP: None
  selector:
    app: postgres
