apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: todo
data:
    password: ENC[AES256_GCM,data:4VJMIUMt/HNcXj45,iv:78oyj3GdiBYwOy6xpERQCu1D2QcBZYw/6Ky/oP2DZHk=,tag:d5d/Y5+flOkCjnCab3lrbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6608d8pzlhz0ffh8tlnax4mj0g7q4f3wggd68el69ruyhaegv0s9f5e9n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdzdaRGkrdXIrU1lROUF1
            WURvdzQrdlhDT0JOdkRhdWd2bVl0L1NPaVRJCmt5VmJKK1d5bFBwaU1lYkFYS25z
            OHN4L1NNWnN2THB4Q2NjOXpzb29mT0EKLS0tIEJiMFlJUlRJNUQydm9PVUhZT2c2
            NzVFR2RhN2tYbnd3L0FDYVRzMVJPMTQKJ48DGjcQCK37UgR/cHX4TDhnKqgF0E1s
            bVCyxTDmFv0g+vMY7ArkBcaKUvpUxiPwrQ/JBc8VuquG5fWnWCsrkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-19T12:59:57Z"
    mac: ENC[AES256_GCM,data:oP6rHPt1FWhNEnpviOehUqoAoxBFwo3OPmzFzLRmS/9y1LT4EBUYc73wmGgH3EJw5GpMUe3OaYfUUt4iuYyJxS+D08ol2jR4EOOnHtGO1qTSON5z6TprrLDoBkH7J7xz06VFwA9n/9ZRVVj7WMq/Hh3LKMBNJzCr9R3Lu58xHFU=,iv:M68anyHy5iPj3XwGxj/e9EkJ8V3zhU6rxw6tQB4y3x4=,tag:YN5djl7yMXF91KGA2ZTobg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
