apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: ollikarppinen/todo
          imagePullPolicy: Always
          env:
            - name: PERSISTED_IMAGE_PATH
              value: /app/shared-image/image.jpg
          volumeMounts:
            - name: shared-image
              mountPath: /app/shared-image
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: shared-pv-claim
