apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-publisher-dep
  namespace: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-publisher
  template:
    metadata:
      labels:
        app: todo-publisher
    spec:
      containers:
        - name: todo-publisher
          image: PROJECT/IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "150m"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-secret
                  key: bot_token
                  optional: false
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: telegram-secret
                  key: chat_id
                  optional: false
