apiVersion: v1
kind: Secret
metadata:
    name: telegram-secret
    namespace: todo
stringData:
    bot_token: ENC[AES256_GCM,data:KPM03nfqhJ3LfBE/tvJG3viPhxUZEwtWyx4r9emrCIB1qW96zCx8zOhUBFf5OQ==,iv:nmHSLTjdwInetXfOalBbuDqf5llUClKCr0cPvOh+59A=,tag:HNPPGL5NOrrwO2XVCpTlEA==,type:str]
    chat_id: ENC[AES256_GCM,data:Y3b7+KlDHHPWjA==,iv:8JIUTcCR8xxvw3ygFzAMSPTzJTFTzjVEKjHAtAi4zT4=,tag:4fhCqbrNi2odvWSIXFshuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k6608d8pzlhz0ffh8tlnax4mj0g7q4f3wggd68el69ruyhaegv0s9f5e9n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArU3pYNDlxaGpFNFlJQ3Yv
            TWlPbnVJOTNTeEJQOCtUZXNabFduV1c0c2dzClVDdUNNRlN0WnZwU1QwTy9TaXZW
            T0loNitWTEg4VHpwQ3dNc0ZKQTEwUzQKLS0tIHdxYTVweTV2V2dWU0ttbDVhN2c4
            VXYvQnhIcS80R0J0ZVNKZkVVR2dCencKXsIFDHzKNq08vvqhNqthRTjoA9m9Ml1p
            LgTHCkJrU9Kp31M96Py7jQoGpwMS5GtoqzYdSgLQZpkdBylP5BhBnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-27T06:56:28Z"
    mac: ENC[AES256_GCM,data:BgoVAdYasSImSX4oU4s3OrDIMV3S1SdIj/lQ1NBtoYcxwdH+EbFmDwUu14kldCJqRJjqmMhIjsiIb3lAr11DDCOX2mPijDdTUhbvDCNN18ygRgzYjjhkFQ9L5sjAFWxmt3TlkImpZ/lYTr8Vw9kUKOVHhBvop3sbLlb3866WvWs=,iv:7OqMGBKNdBv2T4Q26C3U3DNUstHcq8jd7CoHkx73GEA=,tag:c59fgJ1+wd4QAuYoyjnKLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
