name: Delete Todo project
on: [delete]
env:
  GKE_CLUSTER: dev-ops-with-kubernetes-cluster
  GKE_ZONE: europe-north1-b
jobs:
  delete-namespace:
    name: Delete namespace
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Delete namespace
        run: |-
          kubectl delete namespace "todo-${GITHUB_REF_NAME}" || true
